version: '2'

services:
    web:
        build: docker/nginx
        ports:
            - "8080:80"
        volumes:
            - .:/code
        networks:
            - code-network
    php:
        build: docker/php
        volumes:
            - .:/code
        networks:
            - code-network
    mysql:
        image: mysql:8.0
        volumes:
          - ./code
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=slim_app_db
            - MYSQL_USER=slim_user
            - MYSQL_PASSWORD=root
        ports:
          - "8082:3306"
        networks:
          - code-network

networks:
    code-network:
        driver: bridge
